package Progra;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author megan
 */
public class Quiosco extends javax.swing.JFrame {

    
    /**
     * Creates new form Quiosco
     */
    int Contador=0;
    int ActualPerecederos=1; 
    int ActualNP=1;
    int ActualS=1;
     
    public Quiosco() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Courier TEC");
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblQuiskoAuto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lbltUsuario = new javax.swing.JLabel();
        cbxtUsuario = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        lbltPaquete = new javax.swing.JLabel();
        cbxtPaquete = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblNombre2 = new javax.swing.JLabel();
        lblSolicitarNombre = new javax.swing.JLabel();
        lblNficha = new javax.swing.JLabel();
        lblSoliNficha = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnFicha = new javax.swing.JButton();
        Nombre = new javax.swing.JLabel();
        Ficha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Perecederos_Ventana = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NP_Ventanas = new javax.swing.JTable();
        btnAtenderP = new javax.swing.JButton();
        btnLAP = new javax.swing.JButton();
        btnAtenderNP = new javax.swing.JButton();
        btnLANP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        S_Ventanas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnInicSeg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Cant_Perecederos = new javax.swing.JTextField();
        btnAñadirP = new javax.swing.JButton();
        Cant_NP = new javax.swing.JTextField();
        btnAñadirNP = new javax.swing.JButton();
        Cant_Seg = new javax.swing.JTextField();
        btnAñadirS = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 197, 109));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblQuiskoAuto.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        lblQuiskoAuto.setText("Quisko de autoservicio");

        lblNombre.setText("Nombre:");

        lblCorreo.setText("Correo:");

        lbltUsuario.setText("Tipo de usuario:");

        cbxtUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discapacitado", "Embarazada", "Adulto Mayor", "Regular" }));
        cbxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtUsuarioActionPerformed(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lbltPaquete.setText("Tipo de paquete:");

        cbxtPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perecederos", "No perecederos" }));

        jPanel1.setBackground(new java.awt.Color(97, 244, 166));

        lblNombre2.setText("Nombre:");

        lblNficha.setText("No. de ficha:");

        btnAgregar.setText("Agregar a cola");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnFicha.setText("Solicitar ficha");
        btnFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFichaActionPerformed(evt);
            }
        });

        Nombre.setText("-");

        Ficha.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNficha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ficha, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoliNficha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSolicitarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnFicha)
                .addGap(44, 44, 44)
                .addComponent(btnAgregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombre2)
                        .addComponent(lblSolicitarNombre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNficha)
                    .addComponent(lblSoliNficha)
                    .addComponent(Ficha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnFicha))
                .addContainerGap())
        );

        Perecederos_Ventana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane1.setViewportView(Perecederos_Ventana);

        jLabel1.setText("Perecederos");

        jLabel2.setText("No perecederos");

        NP_Ventanas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane2.setViewportView(NP_Ventanas);

        btnAtenderP.setText("Atender");

        btnLAP.setText("Liberar y Atender");

        btnAtenderNP.setText("Atender");

        btnLANP.setText("Liberar y Atender");

        S_Ventanas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ventanilla", "Estado"
            }
        ));
        jScrollPane3.setViewportView(S_Ventanas);

        jLabel3.setText("Seguridad");

        btnInicSeg.setText("Iniciar");

        jButton1.setText("Administrador");

        btnAñadirP.setText("Añadir");
        btnAñadirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPActionPerformed(evt);
            }
        });

        btnAñadirNP.setText("Añadir");
        btnAñadirNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirNPActionPerformed(evt);
            }
        });

        btnAñadirS.setText("Añadir");
        btnAñadirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblCorreo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblQuiskoAuto))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltPaquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxtPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Cant_Seg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAñadirS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(228, 228, 228)
                            .addComponent(btnInicSeg))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Cant_NP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAñadirNP, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtenderNP)
                                .addGap(15, 15, 15)
                                .addComponent(btnLANP))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(359, 359, 359))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Cant_Perecederos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAñadirP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtenderP)
                                .addGap(18, 18, 18)
                                .addComponent(btnLAP))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblQuiskoAuto)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxtPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltPaquete))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltUsuario)
                            .addComponent(cbxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAtenderP)
                            .addComponent(btnLAP)
                            .addComponent(Cant_Perecederos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAñadirP))
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtenderNP)
                        .addComponent(btnLANP))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cant_NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAñadirNP)))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicSeg)
                    .addComponent(Cant_Seg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadirS))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cbxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtUsuarioActionPerformed

    private void btnFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFichaActionPerformed
        // TODO add your handling code here:
       String Nombre_usuario=txtNombre.getText();
       Nombre.setText(Nombre_usuario);
       String paquete="";
       String paquete_seleccionado= (String) cbxtPaquete.getSelectedItem();
       
       if(paquete_seleccionado.equals("No perecederos")){
           paquete="NP";
        }
       if(paquete_seleccionado.equals("Perecederos")){
       paquete="P";
       }
       
       String usuario_seleccionado= (String) cbxtUsuario.getSelectedItem();
       String usuario = "";
       if(usuario_seleccionado.equals("Discapacitado")){
           usuario="D";
       }
       if(usuario_seleccionado.equals("Regular")){
           usuario="R";
       }
       if(usuario_seleccionado.equals("Embarazada")){
         usuario="E";  
       }
       if(usuario_seleccionado.equals("Adulto Mayor")){
           usuario="M";
       }
       
       int Numero_Tiquete=this.Contador;
       Ficha.setText(paquete+"-"+usuario+"-"+Numero_Tiquete);
       
       
    }//GEN-LAST:event_btnFichaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAñadirPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPActionPerformed
        // TODO add your handling code here:
        int Cantidad= (Integer.parseInt(Cant_Perecederos.getText()));
        int i;
        System.out.println(Cantidad);
        DefaultTableModel TablaPerecederos= (DefaultTableModel) Perecederos_Ventana.getModel();
        int Inicio=ActualPerecederos; 
        for(i=Cantidad;i>0;i--){
            System.out.println(i);
            TablaPerecederos.addRow(new Object[]{"#"+Inicio,"Libre"});
            Inicio++;
            ActualPerecederos=Inicio;
        }
    }//GEN-LAST:event_btnAñadirPActionPerformed

    private void btnAñadirNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirNPActionPerformed
        // TODO add your handling code here:
        int Cantidad= (Integer.parseInt(Cant_NP.getText()));
        int i;
        System.out.println(Cantidad);
        DefaultTableModel TablaNP= (DefaultTableModel) NP_Ventanas.getModel();
        int Inicio=ActualNP; 
        for(i=Cantidad;i>0;i--){
            System.out.println(i);
            TablaNP.addRow(new Object[]{"#"+Inicio,"Libre"});
            Inicio++;
            ActualNP=Inicio;
        }
    }//GEN-LAST:event_btnAñadirNPActionPerformed

    private void btnAñadirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirSActionPerformed
        // TODO add your handling code here:
        int Cantidad= (Integer.parseInt(Cant_Seg.getText()));
        int i;
        System.out.println(Cantidad);
        DefaultTableModel TablaSeguridad= (DefaultTableModel) S_Ventanas.getModel();
        int Inicio=ActualS; 
        for(i=Cantidad;i>0;i--){
            System.out.println(i);
            TablaSeguridad.addRow(new Object[]{"#"+Inicio,"Libre"});
            Inicio++;
            ActualS=Inicio;
        }
    }//GEN-LAST:event_btnAñadirSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiosco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiosco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cant_NP;
    private javax.swing.JTextField Cant_Perecederos;
    private javax.swing.JTextField Cant_Seg;
    private javax.swing.JLabel Ficha;
    private javax.swing.JTable NP_Ventanas;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTable Perecederos_Ventana;
    private javax.swing.JTable S_Ventanas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAtenderNP;
    private javax.swing.JButton btnAtenderP;
    private javax.swing.JButton btnAñadirNP;
    private javax.swing.JButton btnAñadirP;
    private javax.swing.JButton btnAñadirS;
    private javax.swing.JButton btnFicha;
    private javax.swing.JButton btnInicSeg;
    private javax.swing.JButton btnLANP;
    private javax.swing.JButton btnLAP;
    private javax.swing.JComboBox<String> cbxtPaquete;
    private javax.swing.JComboBox<String> cbxtUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNficha;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblQuiskoAuto;
    private javax.swing.JLabel lblSoliNficha;
    private javax.swing.JLabel lblSolicitarNombre;
    private javax.swing.JLabel lbltPaquete;
    private javax.swing.JLabel lbltUsuario;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
